// micro-FE/packages/cart/src/components/card.svelte
<script lang="ts">
  import type { IProduct } from "common";
  import Button from "./button.svelte";

  interface Item {
    product: IProduct;
    quantity: number;
  }

  export let data: Item;
  export let onRemove: (data: IProduct) => void;

  const currencyFmt = new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  });
</script>

<div class="item">
  <div class="item--image">
    <img
      src={data.product.image.url}
      alt={data.product.name}
      width={data.product.image.width}
      height={data.product.image.height}
    />
  </div>

  <div class="item--info">
    <p class="item--name">{data.product.name}</p>
    <p class="item--price">{currencyFmt.format(data.product.price)}</p>
    <p class="item--quantity">Quantity: {data.quantity}</p>
    <p class="item--total">Total: {currencyFmt.format(data.product.price * data.quantity)}</p>

    <div class="item--action">
      <Button
        on:click={() => {
          onRemove(data.product);
        }}
      >
        Remove
      </Button>
    </div>
  </div>
</div>

<style>
  .item {
    display: flex;
    gap: 2rem;
  }

  .item--image {
    display: flex;
  }

  .item--name {
    font-size: 1.5rem;
  }

  .item--price {
    font-size: 1.2rem;
  }

  .item--quantity {
    margin-top: 1rem;
  }

  .item--action {
    margin-top: 2rem;
  }
</style>

// micro-FE/packages/shop/components/card/card.tsx
import { IProduct, useAuthContext, useCartContext } from "common";
import Image from "next/image";
import styles from "./card.module.css";

export default function Card({ data }: { data: IProduct }) {
  const cart = useCartContext();
  const auth = useAuthContext();

  return (
    <div className={styles["card"]}>
      <div className={styles["card--body"]}>
        <div className={styles["card--image"]}>
          <Image
            src={data.image.url}
            alt={data.name}
            width={data.image.width}
            height={data.image.height}
          />
        </div>

        {auth.isAuthorized && (
          <button
            className={styles["card--action"]}
            onClick={() => {
              cart.add(data, 1);
            }}
          >
            Add to Cart
          </button>
        )}
      </div>

      <div className={styles["card--foot"]}>
        <div className={styles["card--info"]}>
          <p>{data.name}</p>
          <p>{formatter.format(data.price)}</p>
        </div>
      </div>
    </div>
  );
}

const formatter = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
});
